sse:
  actuator:
    users:
      # username = password
      - username: actuator
        password-sha-256: 425edd11c26ae24d6726f66925c024ad7978400bd4ebb10bc943854ab93b3778
      - username: prometheus
        password-sha-256: 1809f7cd0c75acf34f56d8c19782b99c6b5fcd14128a3cc79aca38a4f94af3ff
        allowed-endpoints:
          - prometheus

server:
  servlet:
    session:
      persistence: false # Spring Boot property
      persistent: false # Tomcat property
      cookie:
        secure: false

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: supercoolpassword
  security:
    oauth2:
      client:
        registration:
          local:
            client-name: Local
            client-id: client-id
            client-secret: client-secret
            scope: openid,profile,email,offline_access
        provider:
          local:
            issuer-uri: http://localhost:4011
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
