<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>software.xdev.tci</groupId>
		<artifactId>src</artifactId>
		<version>4.5.0-SNAPSHOT</version>
	</parent>

	<artifactId>bom</artifactId>
	<packaging>pom</packaging>

	<name>bom</name>
	<description>TCI - BOM</description>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>base</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>db-jdbc</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>db-jdbc-spring-orm</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>db-jdbc-spring-orm-eclipselink</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>db-jdbc-spring-orm-hibernate</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>image-build</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>jacoco</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>jul-to-slf4j</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>junit-jupiter-api-support</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>mailpit</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>mockserver</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>oidc-server-mock</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>selenium</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.tci</groupId>
				<artifactId>spring-dao-support</artifactId>
				<version>4.5.0-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
